# Generated by Django 5.0.3 on 2025-11-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField()),
                ('eer', models.FloatField()),
                ('protein_min_g', models.FloatField()),
                ('protein_max_g', models.FloatField()),
                ('fat_min_g', models.FloatField()),
                ('fat_max_g', models.FloatField()),
                ('carbs_min_g', models.FloatField()),
                ('carbs_max_g', models.FloatField()),
                ('vitamins', models.JSONField()),
                ('minerals', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
