# Generated by Django 5.0.3 on 2025-11-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kcal_per_100g', models.FloatField(default=0.0)),
                ('protein_g_per_100g', models.FloatField(default=0.0)),
                ('fat_g_per_100g', models.FloatField(default=0.0)),
                ('carbs_g_per_100g', models.FloatField(default=0.0)),
                ('micronutrients', models.JSONField(blank=True, default=dict)),
                ('density_g_per_ml', models.FloatField(blank=True, help_text='optional; g per ml', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_serving_g', models.FloatField(blank=True, help_text='grams', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutrient_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.nutrientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7'), (8, 'Day 8'), (9, 'Day 9'), (10, 'Day 10'), (11, 'Day 11'), (12, 'Day 12'), (13, 'Day 13'), (14, 'Day 14')])),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('serving_g', models.FloatField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem')),
            ],
            options={
                'unique_together': {('day_index', 'meal_type', 'menu_item')},
            },
        ),
    ]
